# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=2048)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big'), ('gigantic', 'Gigantic')], max_length=7)),
                ('speed', models.PositiveSmallIntegerField()),
                ('vision', models.CharField(max_length=128)),
                ('languages', models.CharField(max_length=128)),
                ('skills', models.CharField(max_length=128)),
                ('abilities', models.CharField(max_length=128)),
                ('traits', models.CharField(max_length=128)),
            ],
        ),
    ]
