# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0002_races_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='', max_length=512)),
            ],
        ),
    ]
