# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 10:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0003_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='race',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
