# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0006_auto_20180202_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='class_spell',
        ),
    ]
