# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0007_remove_spell_class_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='ability',
            field=models.CharField(default='strength', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='aim',
            field=models.CharField(default='one creature', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='attack',
            field=models.CharField(default='1d20', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='damage',
            field=models.CharField(default='1d8', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='other',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
