# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0009_auto_20180202_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='miss',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='other',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
