# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0010_auto_20180202_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='attack_again',
            new_name='attack_against',
        ),
        migrations.AlterField(
            model_name='spell',
            name='other',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
