# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0011_auto_20180202_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='aim',
            field=models.CharField(max_length=64),
        ),
    ]
