# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 09:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0014_load_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroclass',
            name='base_hits',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='heroclass',
            name='description',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroclass',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='heroclass',
            name='healing_depends_on',
            field=models.CharField(choices=[(b'charisma', b'Charisma'), (b'constitution', b'Constitution'), (b'dexterity', b'Dexterity'), (b'intelligence', b'Intelligence'), (b'strength', b'Strength'), (b'wisdom', b'Wisdom')], default='strength', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroclass',
            name='healing_per_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroclass',
            name='hits_depends_on',
            field=models.CharField(choices=[(b'charisma', b'Charisma'), (b'constitution', b'Constitution'), (b'dexterity', b'Dexterity'), (b'intelligence', b'Intelligence'), (b'strength', b'Strength'), (b'wisdom', b'Wisdom')], default='constitution', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroclass',
            name='hits_per_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroclass',
            name='power_source',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroclass',
            name='role',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
