# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.SmallIntegerField(default=25)),
                ('height', models.SmallIntegerField(default=180)),
                ('weight', models.SmallIntegerField(default=80)),
                ('organization', models.CharField(max_length=40)),
            ],
        ),
    ]
