# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_library', '0002_races_initial_data'),
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='charisma',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='hero',
            name='constitution',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='hero',
            name='dexterity',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='hero',
            name='intelligence',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='hero',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dnd_library.Race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='hero',
            name='wisdom',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='hero',
            name='organization',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
