# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_coins', models.PositiveIntegerField(default=0)),
                ('silver_coins', models.PositiveIntegerField(default=0)),
                ('copper_coins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeroInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='', max_length=512)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dnd.HeroInventory')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='ability_points',
            field=models.PositiveSmallIntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='agility',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='charisma',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='constitution',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='intelligence',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='wisdom',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='dnd.HeroInventory'),
        ),
    ]
