# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_auto_20171125_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='inventory',
        ),
        migrations.AddField(
            model_name='heroinventory',
            name='hero',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='dnd.Hero'),
            preserve_default=False,
        ),
    ]
