# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20180201_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
