# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20171125_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroinventoryitem',
            name='inventory',
        ),
        migrations.DeleteModel(
            name='HeroInventoryItem',
        ),
    ]
