# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0005_auto_20180201_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='armor',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='armor_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='fortitude_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='hp_bonus',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='hp_per_lvl',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='reflex_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='shield',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='will_modifier',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herojournalrecord',
            name='tags',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='herojournalrecord',
            name='text',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
