# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0006_heroinventory_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='current_hp',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
