# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_hero_current_hp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='agility',
            new_name='dexterity',
        ),
    ]
