# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0011_auto_20180201_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='ability_points',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='agility',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='current_hp',
        ),
        migrations.AddField(
            model_name='hero',
            name='armor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='armor_modifier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='fortitude_modifier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='hit_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='hp_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='hp_per_lvl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='reflex_modifier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='shield',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='will_modifier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
