# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0014_auto_20180202_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='journal_records',
            field=models.ManyToManyField(blank=True, related_name='heroes', to='dnd.HeroJournalRecord'),
        ),
    ]
