# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0015_auto_20180202_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinventory',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='inventories', to='dnd_library.InventoryItem'),
        ),
    ]
