# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0016_auto_20180202_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='hit_points',
            new_name='damage_taken',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='hp_bonus',
            new_name='hp_permanent_bonus',
        ),
        migrations.AddField(
            model_name='hero',
            name='hp_tmp_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
