# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0017_auto_20180205_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='healings_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
